# Generated by Django 5.2.1 on 2025-06-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_document_alter_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
